### ISSUE TITLE
Comments on first read

### ISSUE THREAD

**Issue by macdroid53** [y1n-dev/FreeCad-Tutorials-and-Examples#1]
Nice!!
Some comments:

I was just dinged by a user that I didn't mention the version of FreeCAD I used for the tutorial.

In the 1st page, 3rd paragraph "Things went easy when you have..." should probably read "Things go easy when you have..."

Rather than referring to "the icon that looks like", etc. you can include the artwork for the actual icons from here:
[https://wiki.freecadweb.org/Artwork](url)
for the Fx blue ball: [https://wiki.freecadweb.org/Artwork_Gui](url)

**Comment by y1n-dev** [comment]
everything done! thank you!
https://github.com/y1n-dev/FreeCad-Tutorials-and-Examples/blob/main/TUTORIAL%20SIMPLE%20FULLY%20PARAMETRIC%20DESIGN%20WITH%20NAMED%20CONSTRAINTS%20IN%20FREECAD.pdf
